Add salesforce onboarding guide and image.
sesamesoftware/DeploymentGuide pull request #128
Opened 2021-07-26 20:23 UTC by david-collins-sesame

Added salesforce datasource onboarding guide.

2021-07-27 01:43 UTC, williamdubberley commented
too many un required fields, basic information not all the fields
saleforce required fields are 
Username
password
and security token if not whitelisting

everythig else is optional. keep it simple

2021-07-29 13:29 UTC, williamdubberley requested changes
on this guide remove the extra information in section datasource information. just the basic username passwords and token.  and add that token cna be omited if using whitelists in salesforce

2021-07-29 17:16 UTC, david-collins-sesame commented
Scott told me he had been making them with all info underneath and only put
the required fields in the required fields list so I had done it this way,
just a heads up for any that he has done.

David Collins

Sesame Software

Tel: (931) 309-0996

5201 Great America Pkwy, Suite 320 Santa Clara, CA 95054
<https://maps.google.com/?q=5201+Great+America+Pkwy,+Suite+320+Santa+Clara,+CA+95054&entry=gmail&source=g>



On Thu, Jul 29, 2021 at 8:30 AM williamdubberley ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> on this guide remove the extra information in section datasource
> information. just the basic username passwords and token. and add that
> token cna be omited if using whitelists in salesforce
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sesamesoftware/DeploymentGuide/pull/128#pullrequestreview-718094762>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUT2WDOGWCMT3DVPPMSIDCLT2FJWDANCNFSM5BA2IQSQ>
> .
>

2021-07-29 17:26 UTC, williamdubberley approved these changes

2021-08-04 16:44 UTC, colenewell approved these changes

2021-08-04 17:14 UTC, merged